spring.application.name=MemberShip


# Database
spring.datasource.url=jdbc:mysql://localhost:3306/membership
spring.datasource.username=root
spring.datasource.password=7004765580@Mk

tier.silver.minOrders=3
tier.gold.minOrders=6
tier.platinum.minOrders=10
tier.gold.minSpend=5000
tier.platinum.minSpend=10000
tier.gold.cohorts=STUDENT
tier.platinum.cohorts=HNI,INFLUENCER